services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - msa-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411" 
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge
